name: Akisam 

on:
  push:
  schedule:
    - cron: '0 * * * *'

permissions:       # <--- ADD THESE TWO LINES
  contents: write  # <--- THIS GIVES THE BOT PERMISSION TO POST FILES

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # ... the rest of your steps ...
